<?php
/**
 * The template for displaying archive pages for the 'project' post type
 */

get_header(); ?>

<?php include_once(get_stylesheet_directory() . '/assets/svg/water-elements.svg'); ?>

<div id="primary" class="content-area project-archive-page">
    <main id="main" class="site-main project-archive-container" role="main">
        <!-- Hero Section with Water Effect -->
        <header class="project-archive-header nts-page-header water-effect-header" data-animate="fadeInUp">
            <div class="water-bg" style="background-color: #0078AA;"></div>

            <!-- Thêm mẫu nước nền -->
            <div class="water-pattern-bg">
                <svg width="100%" height="100%" preserveAspectRatio="none">
                    <use xlink:href="#water-pattern-bg" class="water-pattern"></use>
                </svg>
            </div>

            <!-- SVG Molecules nổi -->
            <div class="chemical-container">
                <svg class="chemical-molecules-svg" width="120" height="120">
                    <use xlink:href="#chemical-molecules"></use>
                </svg>
            </div>

            <!-- Water particles effect -->
            <div class="water-particles-effect">
                <div class="particle-container">
                    <!-- Dynamic particles will be generated by JS -->
                </div>
            </div>

            <div class="bubbles-container">
                <div class="bubble bubble-1"></div>
                <div class="bubble bubble-2"></div>
                <div class="bubble bubble-3"></div>
                <div class="bubble bubble-4"></div>
                <div class="bubble bubble-5"></div>
                <div class="bubble bubble-6"></div>
                <div class="bubble bubble-7"></div>
                <div class="bubble bubble-8"></div>
                <div class="bubble bubble-9"></div>
                <div class="bubble bubble-10"></div>

                <!-- Thêm hiệu ứng Splash -->
                <div class="splash-container">
                    <svg class="water-splash-svg" width="80" height="80">
                        <use xlink:href="#water-splash"></use>
                    </svg>
                </div>
            </div>

            <div class="container">
                <div class="project-header-content service-header-content">
                    <!-- Animated Droplet Icon -->
                    <div class="animated-droplet-icon">
                        <svg width="60" height="90">
                            <use xlink:href="#animated-water-drop"></use>
                        </svg>
                    </div>

                    <h1 class="page-title">Dự án</h1>
                    <p class="page-description">Khám phá các dự án xử lý nước tiêu biểu của chúng tôi với công nghệ tiên tiến và giải pháp hiệu quả. Mỗi dự án là minh chứng cho cam kết mang đến nguồn nước sạch, an toàn và bền vững.</p>

                    <!-- Project Stats -->
                    <div class="project-stats">
                        <?php
                        $total_projects = wp_count_posts('project')->publish;
                        $categories = get_terms(array(
                            'taxonomy' => 'project_category',
                            'hide_empty' => true,
                        ));
                        $category_count = count($categories);
                        ?>
                        <div class="stat-item">
                            <div class="stat-icon"><i class="fa fa-tasks"></i></div>
                            <div class="stat-content">
                                <div class="stat-number"><?php echo esc_html($total_projects); ?></div>
                                <div class="stat-label">Dự án</div>
                            </div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-icon"><i class="fa fa-folder-open"></i></div>
                            <div class="stat-content">
                                <div class="stat-number"><?php echo esc_html($category_count); ?></div>
                                <div class="stat-label">Danh mục</div>
                            </div>
                        </div>
                    </div>

                    <!-- Scroll Down Indicator -->
                    <div class="scroll-down-indicator">
                        <div class="mouse-icon">
                            <div class="wheel"></div>
                        </div>
                        <div class="scroll-text">Cuộn xuống</div>
                    </div>
                </div>
            </div>

            <!-- Wave Decoration -->
            <div class="wave-decoration">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                    <path fill="#f0f8ff" fill-opacity="0.8" d="M0,192L48,176C96,160,192,128,288,122.7C384,117,480,139,576,149.3C672,160,768,160,864,138.7C960,117,1056,75,1152,69.3C1248,64,1344,96,1392,112L1440,128L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path>
                </svg>
            </div>
        </header><!-- .page-header -->

        <div class="container">
            <!-- Project Categories Section -->
            <section class="project-categories-section">
                <h2 class="section-title">Danh mục dự án</h2>
                <div class="project-categories-grid">
                    <?php
                    $categories = get_terms(array(
                        'taxonomy' => 'project_category',
                        'hide_empty' => true,
                    ));

                    if (!empty($categories) && !is_wp_error($categories)) :
                        foreach ($categories as $category) :
                            $category_image_id = get_term_meta($category->term_id, 'category_image', true);
                            $category_image_url = $category_image_id ? wp_get_attachment_image_url($category_image_id, 'medium') : '';
                            $category_link = get_term_link($category);
                            ?>
                            <a href="<?php echo esc_url($category_link); ?>" class="category-card">
                                <div class="category-card-image">
                                    <?php if (!empty($category_image_url)) : ?>
                                        <img src="<?php echo esc_url($category_image_url); ?>" alt="<?php echo esc_attr($category->name); ?>">
                                    <?php else : ?>
                                        <div class="category-icon">
                                            <i class="fa fa-water"></i>
                                        </div>
                                    <?php endif; ?>
                                    <div class="category-overlay"></div>
                                </div>
                                <div class="category-card-content">
                                    <h3><?php echo esc_html($category->name); ?></h3>
                                    <span class="category-count"><?php echo esc_html($category->count); ?> dự án</span>
                                </div>
                            </a>
                            <?php
                        endforeach;
                    endif;
                    ?>
                </div>
            </section>

            <!-- Project Filter Section -->
            <section class="project-filter-section">
                <div class="filter-header">
                    <h2 class="section-title">Tất cả dự án</h2>
                    <div class="filter-controls">
                        <div class="filter-dropdown">
                            <button class="filter-button">
                                <i class="fa fa-filter"></i> Lọc dự án
                            </button>
                            <div class="filter-dropdown-content">
                                <a href="<?php echo esc_url(get_post_type_archive_link('project')); ?>" class="filter-item active">Tất cả</a>
                                <?php
                                if (!empty($categories) && !is_wp_error($categories)) :
                                    foreach ($categories as $category) :
                                        ?>
                                        <a href="<?php echo esc_url(get_term_link($category)); ?>" class="filter-item">
                                            <?php echo esc_html($category->name); ?>
                                        </a>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                            </div>
                        </div>
                        <div class="view-toggle">
                            <button class="view-button grid-view active" data-view="grid">
                                <i class="fa fa-th-large"></i>
                            </button>
                            <button class="view-button list-view" data-view="list">
                                <i class="fa fa-list"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <?php if (have_posts()) : ?>
                    <div class="project-archive row" id="project-grid">
                        <?php
                        /* Start the Loop */
                        while (have_posts()) :
                            the_post();

                            // Get project categories
                            $project_categories = get_the_terms(get_the_ID(), 'project_category');
                            $project_location = get_post_meta(get_the_ID(), 'project_location', true);
                            $project_time = get_post_meta(get_the_ID(), 'project_time', true);
                            ?>
                            <div class="col large-4 medium-6 small-12" data-animate="fadeInUp">
                                <article id="post-<?php the_ID(); ?>" <?php post_class('project-card'); ?>>
                                    <div class="project-item-thumbnail">
                                        <?php if (has_post_thumbnail()) : ?>
                                            <a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>">
                                                <?php the_post_thumbnail('medium_large'); ?>
                                            </a>
                                        <?php else : ?>
                                            <div class="no-thumbnail">
                                                <svg class="water-icon">
                                                    <use xlink:href="#water-treatment"></use>
                                                </svg>
                                            </div>
                                        <?php endif; ?>
                                        <div class="project-item-overlay">
                                            <svg class="hexagon-pattern" width="100%" height="100%">
                                                <use xlink:href="#hexagon-grid"></use>
                                            </svg>
                                            <div class="overlay-content">
                                                <a href="<?php the_permalink(); ?>" class="view-project-btn">
                                                    <i class="fa fa-eye"></i> Xem dự án
                                                </a>
                                            </div>
                                        </div>

                                        <?php if (!empty($project_categories)) : ?>
                                            <div class="project-category-badge">
                                                <?php echo esc_html($project_categories[0]->name); ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="project-item-content">
                                        <h2 class="project-item-title">
                                            <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                                        </h2>

                                        <?php if (!empty($project_location) || !empty($project_time)) : ?>
                                            <div class="project-item-meta">
                                                <?php if (!empty($project_location)) : ?>
                                                    <div class="meta-item">
                                                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                                                        <span><?php echo esc_html($project_location); ?></span>
                                                    </div>
                                                <?php endif; ?>

                                                <?php if (!empty($project_time)) : ?>
                                                    <div class="meta-item">
                                                        <i class="fa fa-calendar" aria-hidden="true"></i>
                                                        <span><?php echo esc_html($project_time); ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <div class="project-item-excerpt">
                                            <?php echo wp_trim_words(get_the_excerpt(), 15); ?>
                                        </div>

                                        <div class="project-item-readmore">
                                            <a href="<?php the_permalink(); ?>" class="btn-water-ripple">
                                                <span>Chi tiết</span>
                                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </div><!-- .project-item-content -->
                                </article><!-- #post-<?php the_ID(); ?> -->
                            </div>
                            <?php
                        endwhile;
                        ?>
                    </div> <!-- .project-archive-grid -->

                    <!-- List View (Hidden by Default) -->
                    <div class="project-list-view" id="project-list" style="display: none;">
                        <?php
                        // Reset the post data to start the loop again
                        rewind_posts();

                        while (have_posts()) :
                            the_post();

                            // Get project categories
                            $project_categories = get_the_terms(get_the_ID(), 'project_category');
                            $project_location = get_post_meta(get_the_ID(), 'project_location', true);
                            $project_time = get_post_meta(get_the_ID(), 'project_time', true);
                            ?>
                            <article id="post-list-<?php the_ID(); ?>" <?php post_class('project-list-item'); ?>>
                                <div class="project-list-thumbnail">
                                    <?php if (has_post_thumbnail()) : ?>
                                        <a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>">
                                            <?php the_post_thumbnail('thumbnail'); ?>
                                        </a>
                                    <?php else : ?>
                                        <div class="no-thumbnail">
                                            <svg class="water-icon">
                                                <use xlink:href="#water-treatment"></use>
                                            </svg>
                                        </div>
                                    <?php endif; ?>

                                    <?php if (!empty($project_categories)) : ?>
                                        <div class="project-category-badge">
                                            <?php echo esc_html($project_categories[0]->name); ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="project-list-content">
                                    <h2 class="project-list-title">
                                        <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                                    </h2>

                                    <?php if (!empty($project_location) || !empty($project_time)) : ?>
                                        <div class="project-list-meta">
                                            <?php if (!empty($project_location)) : ?>
                                                <div class="meta-item">
                                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                                    <span><?php echo esc_html($project_location); ?></span>
                                                </div>
                                            <?php endif; ?>

                                            <?php if (!empty($project_time)) : ?>
                                                <div class="meta-item">
                                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                                    <span><?php echo esc_html($project_time); ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <div class="project-list-excerpt">
                                        <?php echo wp_trim_words(get_the_excerpt(), 30); ?>
                                    </div>
                                </div>
                                <div class="project-list-action">
                                    <a href="<?php the_permalink(); ?>" class="btn-water-ripple">
                                        <span>Chi tiết</span>
                                        <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </article>
                            <?php
                        endwhile;
                        ?>
                    </div>

                    <?php
                    // Add pagination with custom wrapper class
                    echo '<div class="project-pagination">';
                    the_posts_pagination(array(
                        'mid_size' => 2,
                        'prev_text' => __('‹ Trước', 'textdomain'),
                        'next_text' => __('Sau ›', 'textdomain'),
                    ));
                    echo '</div>';
                else :
                    // If no content, include the "No posts found" template.
                    get_template_part('template-parts/content', 'none');
                endif;
                ?>
            </section>

            <!-- Featured Projects Section -->
            <?php
            $featured_args = array(
                'post_type' => 'project',
                'posts_per_page' => 3,
                'meta_query' => array(
                    array(
                        'key' => 'featured_project',
                        'value' => '1',
                        'compare' => '='
                    )
                )
            );

            $featured_query = new WP_Query($featured_args);

            if ($featured_query->have_posts()) :
            ?>
            <section class="featured-projects-section">
                <h2 class="section-title">Dự án nổi bật</h2>
                <div class="featured-projects-slider">
                    <?php while ($featured_query->have_posts()) : $featured_query->the_post(); ?>
                        <div class="featured-project-slide">
                            <div class="featured-project-image">
                                <?php if (has_post_thumbnail()) : ?>
                                    <?php the_post_thumbnail('large'); ?>
                                <?php else : ?>
                                    <div class="no-thumbnail">
                                        <svg class="water-icon">
                                            <use xlink:href="#water-treatment"></use>
                                        </svg>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="featured-project-content">
                                <h3 class="featured-project-title">
                                    <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                                </h3>
                                <div class="featured-project-excerpt">
                                    <?php echo wp_trim_words(get_the_excerpt(), 25); ?>
                                </div>
                                <a href="<?php the_permalink(); ?>" class="featured-project-link">
                                    Xem chi tiết <i class="fa fa-long-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    <?php endwhile; ?>
                    <?php wp_reset_postdata(); ?>
                </div>
            </section>
            <?php endif; ?>
        </div>
    </main><!-- #main -->
</div><!-- #primary -->

<!-- JavaScript code moved to consolidated.js -->

<?php
get_footer();