<?php
/**
 * The template for displaying archive pages for the 'service' post type
 */

get_header(); ?>

<?php include_once(get_stylesheet_directory() . '/assets/svg/water-elements.svg'); ?>

<div id="primary" class="content-area service-archive-page">
    <main id="main" class="site-main service-archive-container" role="main">
        <!-- Hero Section with Water Effect -->
        <header class="service-archive-header nts-page-header water-effect-header" data-animate="fadeInUp">
            <div class="water-bg"></div>
            
            <!-- Thêm mẫu nước nền -->
            <div class="water-pattern-bg">
                <svg width="100%" height="100%" preserveAspectRatio="none">
                    <use xlink:href="#water-pattern-bg" class="water-pattern"></use>
                </svg>
            </div>
            
            <!-- SVG Molecules nổi -->
            <div class="chemical-container">
                <svg class="chemical-molecules-svg" width="120" height="120">
                    <use xlink:href="#chemical-molecules"></use>
                </svg>
            </div>
            
            <!-- Remove problematic wave container and replace with particle effect -->
            <div class="water-particles-effect">
                <div class="particle-container">
                    <!-- Dynamic particles will be generated by JS -->
            </div>
            </div>
            
            <div class="bubbles-container">
                <div class="bubble bubble-1"></div>
                <div class="bubble bubble-2"></div>
                <div class="bubble bubble-3"></div>
                <div class="bubble bubble-4"></div>
                <div class="bubble bubble-5"></div>
                <div class="bubble bubble-6"></div>
                <div class="bubble bubble-7"></div>
                <div class="bubble bubble-8"></div>
                <div class="bubble bubble-9"></div>
                <div class="bubble bubble-10"></div>
                
                <!-- Thêm hiệu ứng Splash -->
                <div class="splash-container">
                    <svg class="water-splash-svg" width="80" height="80">
                        <use xlink:href="#water-splash"></use>
                    </svg>
                </div>
            </div>
            
            <div class="container">
                <div class="service-header-content">
                    <!-- Animated Droplet Icon -->
                    <div class="animated-droplet-icon">
                        <svg width="60" height="90">
                            <use xlink:href="#animated-water-drop"></use>
                        </svg>
                    </div>
                    
                    <h1 class="page-title">Dịch vụ</h1>
                    <p class="page-description">Giải pháp xử lý nước chuyên nghiệp với công nghệ tiên tiến và đội ngũ chuyên gia hàng đầu. Chúng tôi cam kết mang đến hiệu quả tối ưu cho mọi nhu cầu xử lý nước của khách hàng.</p>
                </div>
            </div>
        </header><!-- .page-header -->


        <div class="container">
            <?php if ( have_posts() ) : ?>


                <div class="service-archive row">

                    <?php
                    /* Start the Loop */
                    while ( have_posts() ) :
                        the_post();

                        ?>
                        <div class="col large-4 medium-6 smail-12" data-animate="fadeInUp">
                            <article id="post-<?php the_ID(); ?>" <?php post_class( 'service-card' ); ?>>
                                <div class="service-item-thumbnail">
                                    <?php if ( has_post_thumbnail() ) : ?>
                                        <a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>">
                                            <?php the_post_thumbnail( 'medium_large' ); // Use an appropriate image size ?>
                                        </a>
                                    <?php else : ?>
                                        <div class="no-thumbnail">
                                            <svg class="water-icon">
                                                <use xlink:href="#water-treatment"></use>
                                            </svg>
                                        </div>
                                    <?php endif; ?>
                                    <div class="service-item-overlay">
                                        <svg class="hexagon-pattern" width="100%" height="100%">
                                            <use xlink:href="#hexagon-grid"></use>
                                        </svg>
                                    </div>
                                </div>
                                <div class="service-item-content">
                                    <h2 class="service-item-title">
                                        <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                                    </h2>
                                    <div class="service-item-excerpt">
                                        <?php the_excerpt(); ?>
                                    </div>
                                    <div class="service-item-readmore">
                                        <a href="<?php the_permalink(); ?>" class="btn-water-ripple">
                                            <span>Chi tiết</span>
                                            <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                </div><!-- .service-item-content -->
                            </article><!-- #post-<?php the_ID(); ?> -->
                        </div>
                        <?php

                    endwhile;
                    ?>
                </div> <!-- .service-archive-grid -->
                <?php

                // Add pagination with custom wrapper class
                echo '<div class="service-pagination">';
                the_posts_pagination( array(
                    'mid_size'  => 2,
                    'prev_text' => __( '‹ Trước', 'textdomain' ), // Replace 'textdomain'
                    'next_text' => __( 'Sau ›', 'textdomain' ),    // Replace 'textdomain'
                ) );
                echo '</div>';

            else :

                // If no content, include the "No posts found" template.
                // You might need to create or adjust content-none.php in your theme
                get_template_part( 'template-parts/content', 'none' );

            endif;
            ?>

        </div>
    </main><!-- #main -->
</div><!-- #primary -->

<script>
jQuery(document).ready(function($) {
    // Create water particles
    function createWaterParticle() {
        var container = $('.particle-container');
        var containerWidth = container.width();
        var containerHeight = container.height();
        
        // Random size
        var size = Math.floor(Math.random() * 6) + 2; // 2px to 8px
        
        // Random position
        var posX = Math.floor(Math.random() * containerWidth);
        var posY = Math.floor(Math.random() * (containerHeight / 3)) + (containerHeight * 2/3); // Only in bottom 1/3
        
        // Create particle element
        var particle = $('<div class="water-particle"></div>');
        particle.css({
            width: size + 'px',
            height: size + 'px',
            left: posX + 'px',
            top: posY + 'px',
            opacity: Math.random() * 0.5 + 0.2
        });
        
        // Add to container
        container.append(particle);
        
        // Add class to activate animation
        particle.addClass('particle-animate');
        
        // Remove particle after animation completes
        setTimeout(function() {
            particle.remove();
        }, 8000);
    }
    
    // Create particles periodically
    setInterval(createWaterParticle, 200);
    
    // Thêm hiệu ứng giọt nước
    function createWaterDroplet() {
        var container = $('.water-droplets-container');
        var containerWidth = container.width();
        var containerHeight = container.height();
        
        // Tạo kích thước ngẫu nhiên
        var size = Math.floor(Math.random() * 40) + 10; // 10px đến 50px
        
        // Tạo vị trí ngẫu nhiên
        var posX = Math.floor(Math.random() * (containerWidth - size));
        var posY = Math.floor(Math.random() * (containerHeight - size));
        
        // Tạo element giọt nước
        var droplet = $('<div class="water-droplet"></div>');
        droplet.css({
            width: size + 'px',
            height: size + 'px',
            left: posX + 'px',
            top: posY + 'px'
        });
        
        // Thêm vào container
        container.append(droplet);
        
        // Thêm class để kích hoạt animation sau một khoảng thời gian ngắn
        setTimeout(function() {
            droplet.addClass('droplet-animate');
            
            // Xóa droplet sau khi animation hoàn tất
            setTimeout(function() {
                droplet.remove();
            }, 3000);
        }, 10);
    }
    
    // Tạo hiệu ứng giọt nước định kỳ
    setInterval(createWaterDroplet, 800);
    
    // Thêm hiệu ứng hover cho service card
    $('.service-card').hover(
        function() {
            $(this).find('.service-item-overlay').css('opacity', 1);
        },
        function() {
            $(this).find('.service-item-overlay').css('opacity', 0);
        }
    );

    // Hiệu ứng xuất hiện tuần tự cho các thẻ dịch vụ
    function animateServiceCards() {
        $('.service-card').each(function(index) {
            var card = $(this);
            setTimeout(function() {
                card.addClass('animated-in');
            }, 150 * index);
        });
    }
    
    // Chạy animation khi trang tải xong
    setTimeout(animateServiceCards, 500);

    // Hiệu ứng particles cho header
    function createParticle() {
        var container = $('.water-effect-header');
        var containerWidth = container.width();
        var containerHeight = container.height();
        
        // Tạo kích thước ngẫu nhiên
        var size = Math.floor(Math.random() * 6) + 2; // 2px đến 8px
        
        // Tạo vị trí ngẫu nhiên
        var posX = Math.floor(Math.random() * containerWidth);
        var posY = Math.floor(Math.random() * containerHeight / 3) + (containerHeight * 2/3); // Chỉ ở 1/3 dưới
        
        // Tạo element particle
        var particle = $('<div class="water-particle"></div>');
        particle.css({
            width: size + 'px',
            height: size + 'px',
            left: posX + 'px',
            top: posY + 'px',
            opacity: Math.random() * 0.5 + 0.2
        });
        
        // Thêm vào container
        container.append(particle);
        
        // Thêm class để kích hoạt animation
        particle.addClass('particle-animate');
        
        // Xóa particle sau khi animation hoàn tất
        setTimeout(function() {
            particle.remove();
        }, 8000);
    }
    
    // Tạo particles định kỳ
    setInterval(createParticle, 200);

    // Thêm hiệu ứng floating cho title
    function floatingAnimation() {
        $('.service-header-content').addClass('float-animation');
    }
    
    // Chạy animation floating
    setTimeout(floatingAnimation, 1000);

    // Hiệu ứng ripple khi click vào nút 
    $('.btn-water-ripple').on('click', function(e) {
        var btn = $(this);
        var btnOffset = btn.offset();
        var xPos = e.pageX - btnOffset.left;
        var yPos = e.pageY - btnOffset.top;

        var ripple = $('<span class="ripple-effect"></span>');
        ripple.css({
            width: btn.width(),
            height: btn.width(),
            top: yPos - (btn.width()/2),
            left: xPos - (btn.width()/2)
        });

        btn.append(ripple);

        setTimeout(function() {
            ripple.remove();
        }, 600);
    });

    // Hiệu ứng hover 3D cho service card
    $('.service-card').on('mousemove', function(e) {
        const card = $(this);
        const cardRect = card[0].getBoundingClientRect();
        const cardWidth = cardRect.width;
        const cardHeight = cardRect.height;
        
        // Tính toán vị trí tương đối của chuột trên thẻ
        const mouseX = e.clientX - cardRect.left;
        const mouseY = e.clientY - cardRect.top;
        
        // Tính góc xoay
        const rotateY = ((mouseX / cardWidth) - 0.5) * 10; // -5 đến 5 độ
        const rotateX = ((mouseY / cardHeight) - 0.5) * -10; // -5 đến 5 độ
        
        // Áp dụng hiệu ứng
        card.css('transform', `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) scale3d(1.02, 1.02, 1.02)`);
    });
    
    // Reset khi ra khỏi thẻ
    $('.service-card').on('mouseleave', function() {
        $(this).css('transform', 'perspective(1000px) rotateX(0) rotateY(0) scale3d(1, 1, 1)');
    });
});
</script>

<?php
get_footer();