<?php
/**
 * The single project template file.
 *
 * @package          NTSE\Templates
 */

get_header();
include_once(get_stylesheet_directory() . '/assets/svg/water-elements.svg');
?>

<div id="content" class="project-single">
    <div class="project-header water-effect-header" data-animate="fadeIn">
        <div class="water-bg"></div>
        
        <!-- Water pattern background -->
        <div class="water-pattern-bg">
            <svg width="100%" height="100%" preserveAspectRatio="none">
                <use xlink:href="#water-pattern-bg" class="water-pattern"></use>
            </svg>
        </div>
        
        <!-- Chemical molecules floating effect -->
        <div class="chemical-container">
            <svg class="chemical-molecules-svg" width="120" height="120">
                <use xlink:href="#chemical-molecules"></use>
            </svg>
        </div>
        
        <!-- Water particles effect -->
        <div class="water-particles-effect">
            <div class="particle-container">
                <!-- Dynamic particles will be generated by JS -->
            </div>
        </div>
        
        <!-- Bubble animation -->
        <div class="bubbles-container">
            <div class="bubble bubble-1"></div>
            <div class="bubble bubble-2"></div>
            <div class="bubble bubble-3"></div>
            <div class="bubble bubble-4"></div>
            <div class="bubble bubble-5"></div>
            <div class="bubble bubble-6"></div>
            <div class="bubble bubble-7"></div>
            <div class="bubble bubble-8"></div>
            <div class="bubble bubble-9"></div>
            <div class="bubble bubble-10"></div>
            
            <!-- Splash effect -->
            <div class="splash-container">
                <svg class="water-splash-svg" width="80" height="80">
                    <use xlink:href="#water-splash"></use>
                </svg>
            </div>
        </div>
        
        <div class="container">
            <div class="row align-bottom">
                <div class="col large-6 medium-12 small-12">
                    <?php
                    nts_the_breadcrumb([
                        'show_post_title' => false
                    ]);
                    ?>
                    <div class="project-title-section">
                        <!-- Animated Water Droplet Icon -->
                        <div class="animated-droplet-icon">
                            <svg width="60" height="90">
                                <use xlink:href="#animated-water-drop"></use>
                            </svg>
                        </div>
                        <h1 class="project-title"><?php the_title(); ?></h1>
                    </div>
                </div>
                <div class="col large-6 medium-12 small-12">
                    <div class="project-thumb">
                        <?php if (has_post_thumbnail()) : ?>
                            <?php the_post_thumbnail('full'); ?>
                        <?php else : ?>
                            <div class="no-thumbnail">
                                <svg class="water-icon">
                                    <use xlink:href="#water-treatment"></use>
                                </svg>
                            </div>
                        <?php endif; ?>
                        <div class="project-overlay">
                            <svg class="hexagon-pattern" width="100%" height="100%">
                                <use xlink:href="#hexagon-grid"></use>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="project-content-container">
        <div class="container">
            <div class="row">
                <div class="col large-8 medium-12 small-12">
                    <div class="project-content">
                        <div class="project-overview">
                            <!-- Thêm hình ảnh minh họa quy trình xử lý nước nếu file tồn tại -->
                            <?php
                            $process_img = get_template_directory_uri() . '/assets/image/water-process-diagram.png';
                            $process_file = get_template_directory() . '/assets/image/water-process-diagram.png';
                            
                            if (file_exists($process_file)) :
                            ?>
                            <div class="process-illustration">
                                <img src="<?php echo esc_url($process_img); ?>" alt="Quy trình xử lý nước" class="process-img">
                            </div>
                            <?php endif; ?>
                            
                            <div class="project-description">
                                <?php
                                // Lấy mô tả dự án từ custom field (nếu có)
                                $project_description = get_post_meta(get_the_ID(), 'project_description', true);
                                if (!empty($project_description)) {
                                    echo wpautop($project_description);
                                }
                                ?>
                            </div>
                        </div>
                        
                        <div class="project-challenges">
                            <h3 class="section-title">
                                <svg class="section-icon" width="24" height="24">
                                    <use xlink:href="#water-drop"></use>
                                </svg>
                                Thách thức
                            </h3>
                            
                            <div class="challenge-content">
                                <?php
                                $challenge_img = get_template_directory_uri() . '/assets/image/water-challenge.jpg';
                                $challenge_file = get_template_directory() . '/assets/image/water-challenge.jpg';
                                
                                if (file_exists($challenge_file)) :
                                ?>
                                <div class="challenge-image">
                                    <img src="<?php echo esc_url($challenge_img); ?>" alt="Thách thức xử lý nước">
                                </div>
                                <?php endif; ?>
                                
                                <div class="challenge-text">
                                    <?php
                                    // Lấy thách thức dự án từ custom field (nếu có)
                                    $project_challenges = get_post_meta(get_the_ID(), 'project_challenges', true);
                                    if (!empty($project_challenges)) {
                                        echo wpautop($project_challenges);
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        
                        <div class="project-solutions">
                            <h3 class="section-title">
                                <svg class="section-icon" width="24" height="24">
                                    <use xlink:href="#water-solution"></use>
                                </svg>
                                Giải pháp
                            </h3>
                            
                            <?php
                            // Lấy giải pháp dự án từ custom field (nếu có)
                            $project_solutions = get_post_meta(get_the_ID(), 'project_solutions', true);
                            if (!empty($project_solutions)) {
                                echo wpautop($project_solutions);
                            }
                            ?>
                            
                            <!-- Thêm biểu đồ giải pháp -->
                            <div class="solution-diagram">
                                <div class="solution-steps">
                                    <div class="solution-step">
                                        <div class="step-icon">
                                            <svg width="40" height="40">
                                                <use xlink:href="#water-analysis"></use>
                                            </svg>
                                        </div>
                                        <h4>Phân tích</h4>
                                        <p>Đánh giá chất lượng và tình trạng nguồn nước</p>
                                    </div>
                                    
                                    <div class="solution-step">
                                        <div class="step-icon">
                                            <svg width="40" height="40">
                                                <use xlink:href="#water-design"></use>
                                            </svg>
                                        </div>
                                        <h4>Thiết kế</h4>
                                        <p>Lập phương án và thiết kế hệ thống phù hợp</p>
                                    </div>
                                    
                                    <div class="solution-step">
                                        <div class="step-icon">
                                            <svg width="40" height="40">
                                                <use xlink:href="#water-implement"></use>
                                            </svg>
                                        </div>
                                        <h4>Triển khai</h4>
                                        <p>Lắp đặt và vận hành hệ thống xử lý nước</p>
                                    </div>
                                    
                                    <div class="solution-step">
                                        <div class="step-icon">
                                            <svg width="40" height="40">
                                                <use xlink:href="#water-monitor"></use>
                                            </svg>
                                        </div>
                                        <h4>Giám sát</h4>
                                        <p>Theo dõi và bảo trì hệ thống thường xuyên</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="project-results">
                            <h3 class="section-title">
                                <svg class="section-icon" width="24" height="24">
                                    <use xlink:href="#water-check"></use>
                                </svg>
                                Kết quả
                            </h3>
                            
                            <div class="results-content">
                                <?php
                                // Lấy kết quả dự án từ custom field
                                $project_results = get_post_meta(get_the_ID(), 'project_results', true);
                                if (!empty($project_results)) {
                                    echo '<div class="results-text">';
                                    echo wpautop($project_results);
                                    echo '</div>';
                                }
                                ?>
                                
                                <!-- Biểu đồ kết quả từ số liệu dự án -->
                                <div class="results-highlights">
                                    <?php
                                    // Hiển thị kết quả độ tinh khiết nếu có
                                    $purity_efficiency = get_post_meta(get_the_ID(), 'project_purity_efficiency', true);
                                    if (!empty($purity_efficiency)) {
                                    ?>
                                    <div class="result-highlight">
                                        <div class="result-icon">
                                            <svg width="36" height="36">
                                                <use xlink:href="#water-quality"></use>
                                            </svg>
                                        </div>
                                        <div class="result-value"><?php echo esc_html($purity_efficiency); ?>%</div>
                                        <div class="result-label">Chất lượng nước</div>
                                    </div>
                                    <?php } ?>
                                    
                                    <div class="result-highlight">
                                        <div class="result-icon">
                                            <svg width="36" height="36">
                                                <use xlink:href="#water-efficiency"></use>
                                            </svg>
                                        </div>
                                        <div class="result-value"><?php echo esc_html(get_post_meta(get_the_ID(), 'project_energy_saving', true) ?: '30'); ?>%</div>
                                        <div class="result-label">Tiết kiệm năng lượng</div>
                                    </div>
                                    
                                    <div class="result-highlight">
                                        <div class="result-icon">
                                            <svg width="36" height="36">
                                                <use xlink:href="#water-recycling"></use>
                                            </svg>
                                        </div>
                                        <div class="result-value"><?php echo esc_html(get_post_meta(get_the_ID(), 'project_water_recycling', true) ?: '85'); ?>%</div>
                                        <div class="result-label">Tái sử dụng nước</div>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- Thêm hình ảnh so sánh trước/sau nếu các hình ảnh tồn tại -->
                            <?php
                            $before_img = get_template_directory_uri() . '/assets/image/water-before.jpg';
                            $after_img = get_template_directory_uri() . '/assets/image/water-after.jpg';
                            
                            // Kiểm tra xem các file hình ảnh có tồn tại không
                            $before_file = get_template_directory() . '/assets/image/water-before.jpg';
                            $after_file = get_template_directory() . '/assets/image/water-after.jpg';
                            
                            if (file_exists($before_file) && file_exists($after_file)) :
                            ?>
                            <div class="before-after-comparison">
                                <h4 class="comparison-title">So sánh trước và sau khi lắp đặt</h4>
                                <div class="comparison-container">
                                    <div class="comparison-item">
                                        <div class="comparison-label">Trước</div>
                                        <div class="comparison-image">
                                            <img src="<?php echo esc_url($before_img); ?>" alt="Trước khi xử lý">
                                        </div>
                                    </div>
                                    
                                    <div class="comparison-item">
                                        <div class="comparison-label">Sau</div>
                                        <div class="comparison-image">
                                            <img src="<?php echo esc_url($after_img); ?>" alt="Sau khi xử lý">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php endif; ?>
                        </div>
                        
                        <?php
                        // Lấy hình ảnh dự án từ custom field (nếu có)
                        $project_gallery = get_post_meta(get_the_ID(), 'project_gallery', true);
                        
                        // Debug: Log gallery data
                        error_log('Project gallery data in single-project.php: ' . print_r($project_gallery, true));
                        
                        if (!empty($project_gallery)) {
                            echo '<div class="project-gallery">';
                            echo '<h3 class="section-title">
                                <svg class="section-icon" width="24" height="24">
                                    <use xlink:href="#water-image"></use>
                                </svg>
                                Hình ảnh dự án
                            </h3>';
                            echo '<div class="gallery-container">';
                            
                            // Kiểm tra nếu gallery là một mảng hoặc có thể chuyển đổi thành mảng
                            $gallery_ids = is_array($project_gallery) ? $project_gallery : explode(',', $project_gallery);
                            
                            // Filter out any empty values
                            $gallery_ids = array_filter($gallery_ids, function($id) {
                                return !empty($id) && is_numeric($id);
                            });
                            
                            // Debug: Log gallery IDs after filtering
                            error_log('Gallery IDs after filtering: ' . implode(',', $gallery_ids));
                            
                            foreach ($gallery_ids as $image_id) {
                                $image_url = wp_get_attachment_image_url($image_id, 'large');
                                $image_full = wp_get_attachment_image_url($image_id, 'full');
                                if ($image_url) {
                                    echo '<div class="gallery-item">';
                                    echo '<a href="' . esc_url($image_full) . '" class="project-gallery-link">';
                                    echo '<img src="' . esc_url($image_url) . '" alt="Project Gallery Image" />';
                                    echo '</a>';
                                    echo '</div>';
                                } else {
                                    error_log('Failed to get image URL for ID: ' . $image_id);
                                }
                            }
                            
                            echo '</div>'; // .gallery-container
                            echo '</div>'; // .project-gallery
                        } else {
                            error_log('No gallery found for project ID: ' . get_the_ID());
                        }
                        ?>
                    </div>
                </div>
                
                <div class="col large-4 medium-12 small-12">
                    <div class="project-sidebar">
                        <div class="project-info-card">
                            <h3 class="card-title">Thông tin dự án</h3>
                            
                            <div class="project-meta">
                                <div class="meta-item">
                                    <div class="meta-icon">
                                        <svg width="20" height="20">
                                            <use xlink:href="#category-icon"></use>
                                        </svg>
                                    </div>
                                    <div class="meta-content">
                                        <div class="meta-label">Danh mục:</div>
                                        <div class="meta-value">
                                            <?php
                                            $terms = get_the_terms(get_the_ID(), 'project_category');
                                            if ($terms && !is_wp_error($terms)) {
                                                $term_links = array();
                                                foreach ($terms as $term) {
                                                    $term_links[] = '<a href="' . esc_url(get_term_link($term)) . '">' . $term->name . '</a>';
                                                }
                                                echo implode(', ', $term_links);
                                            } else {
                                                echo 'Không có danh mục';
                                            }
                                            ?>
                                        </div>
                                    </div>
                                </div>
                                
                                <?php
                                // Lấy địa điểm dự án từ custom field (nếu có)
                                $project_location = get_post_meta(get_the_ID(), 'project_location', true);
                                if (!empty($project_location)) {
                                    echo '<div class="meta-item">';
                                    echo '<div class="meta-icon"><svg width="20" height="20"><use xlink:href="#location-icon"></use></svg></div>';
                                    echo '<div class="meta-content">';
                                    echo '<div class="meta-label">Địa điểm:</div>';
                                    echo '<div class="meta-value">' . esc_html($project_location) . '</div>';
                                    echo '</div>';
                                    echo '</div>';
                                }
                                
                                // Lấy thời gian dự án từ custom field (nếu có)
                                $project_time = get_post_meta(get_the_ID(), 'project_time', true);
                                if (!empty($project_time)) {
                                    echo '<div class="meta-item">';
                                    echo '<div class="meta-icon"><svg width="20" height="20"><use xlink:href="#time-icon"></use></svg></div>';
                                    echo '<div class="meta-content">';
                                    echo '<div class="meta-label">Thời gian:</div>';
                                    echo '<div class="meta-value">' . esc_html($project_time) . '</div>';
                                    echo '</div>';
                                    echo '</div>';
                                }
                                
                                // Lấy công nghệ dự án từ custom field (nếu có)
                                $project_technology = get_post_meta(get_the_ID(), 'project_technology', true);
                                if (!empty($project_technology)) {
                                    echo '<div class="meta-item">';
                                    echo '<div class="meta-icon"><svg width="20" height="20"><use xlink:href="#technology-icon"></use></svg></div>';
                                    echo '<div class="meta-content">';
                                    echo '<div class="meta-label">Công nghệ:</div>';
                                    echo '<div class="meta-value">' . esc_html($project_technology) . '</div>';
                                    echo '</div>';
                                    echo '</div>';
                                }
                                ?>
                            </div>
                        </div>
                        
                        <!-- Statistics Card -->
                        <div class="project-stats-card">
                            <h3 class="card-title">Số liệu dự án</h3>
                            <div class="stats-container">
                                <div class="stat-item">
                                    <div class="stat-value"><?php echo esc_html(get_post_meta(get_the_ID(), 'project_processing_capacity', true) ?: '1500'); ?></div>
                                    <div class="stat-label">m³/ngày</div>
                                    <div class="stat-desc">Công suất xử lý</div>
                                </div>
                                
                                <div class="stat-item">
                                    <div class="stat-value"><?php echo esc_html(get_post_meta(get_the_ID(), 'project_implementation_time', true) ?: '3'); ?></div>
                                    <div class="stat-label">tháng</div>
                                    <div class="stat-desc">Thời gian triển khai</div>
                                </div>
                                
                                <div class="stat-item">
                                    <div class="stat-value"><?php echo esc_html(get_post_meta(get_the_ID(), 'project_system_lifetime', true) ?: '25'); ?></div>
                                    <div class="stat-label">năm</div>
                                    <div class="stat-desc">Tuổi thọ hệ thống</div>
                                </div>
                                
                                <div class="stat-item">
                                    <div class="stat-value"><?php echo esc_html(get_post_meta(get_the_ID(), 'project_purity_efficiency', true) ?: '98'); ?>%</div>
                                    <div class="stat-label">hiệu suất</div>
                                    <div class="stat-desc">Độ tinh khiết</div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="related-projects-card">
                            <h3 class="card-title">Dự án tương tự</h3>
                            
                            <?php
                            // Lấy các dự án liên quan theo category
                            $terms = get_the_terms(get_the_ID(), 'project_category');
                            
                            if ($terms && !is_wp_error($terms)) {
                                $term_ids = array();
                                foreach ($terms as $term) {
                                    $term_ids[] = $term->term_id;
                                }
                                
                                $related_args = array(
                                    'post_type' => 'project',
                                    'posts_per_page' => 3,
                                    'post__not_in' => array(get_the_ID()),
                                    'tax_query' => array(
                                        array(
                                            'taxonomy' => 'project_category',
                                            'field' => 'term_id',
                                            'terms' => $term_ids,
                                        ),
                                    ),
                                );
                                
                                $related_query = new WP_Query($related_args);
                                
                                if ($related_query->have_posts()) {
                                    echo '<div class="related-projects-list">';
                                    
                                    while ($related_query->have_posts()) {
                                        $related_query->the_post();
                                        
                                        echo '<div class="related-project-item">';
                                        echo '<a href="' . get_permalink() . '" class="related-project-link">';
                                        
                                        if (has_post_thumbnail()) {
                                            echo '<div class="related-project-thumb">';
                                            the_post_thumbnail('thumbnail');
                                            echo '</div>';
                                        }
                                        
                                        echo '<div class="related-project-content">';
                                        echo '<h4 class="related-project-title">' . get_the_title() . '</h4>';
                                        echo '</div>';
                                        
                                        echo '</a>';
                                        echo '</div>';
                                    }
                                    
                                    echo '</div>';
                                    wp_reset_postdata();
                                } else {
                                    echo '<p>Không có dự án liên quan.</p>';
                                }
                            }
                            ?>
                        </div>
                        
                        <div class="contact-card">
                            <h3 class="card-title">Bạn cần tư vấn?</h3>
                            <?php
                            $contact_img = get_template_directory_uri() . '/assets/image/contact-water.jpg';
                            $contact_file = get_template_directory() . '/assets/image/contact-water.jpg';
                            
                            if (file_exists($contact_file)) :
                            ?>
                            <div class="contact-image">
                                <img src="<?php echo esc_url($contact_img); ?>" alt="Tư vấn xử lý nước">
                            </div>
                            <?php endif; ?>
                            <p>Liên hệ với chúng tôi để được tư vấn giải pháp xử lý nước phù hợp với nhu cầu của bạn.</p>
                            <a href="<?php echo home_url('/lien-he'); ?>" class="btn btn-contact">
                                <svg class="btn-icon" width="16" height="16">
                                    <use xlink:href="#contact-icon"></use>
                                </svg>
                                Liên hệ ngay
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
jQuery(document).ready(function($) {
    // Create water particles effect
    function createWaterParticle() {
        var container = $('.particle-container');
        var containerWidth = container.width();
        var containerHeight = container.height();
        
        // Random size
        var size = Math.floor(Math.random() * 6) + 2; // 2px to 8px
        
        // Random position
        var posX = Math.floor(Math.random() * containerWidth);
        var posY = Math.floor(Math.random() * (containerHeight / 3)) + (containerHeight * 2/3); // Only in bottom 1/3
        
        // Create particle element
        var particle = $('<div class="water-particle"></div>');
        particle.css({
            width: size + 'px',
            height: size + 'px',
            left: posX + 'px',
            top: posY + 'px',
            opacity: Math.random() * 0.5 + 0.2
        });
        
        // Add to container
        container.append(particle);
        
        // Add class to activate animation
        particle.addClass('particle-animate');
        
        // Remove particle after animation completes
        setTimeout(function() {
            particle.remove();
        }, 8000);
    }
    
    // Create particles periodically
    setInterval(createWaterParticle, 200);
    
    // Initialize lightbox for gallery
    if (typeof $.fn.magnificPopup !== 'undefined') {
        $('.project-gallery-link').magnificPopup({
            type: 'image',
            gallery: {
                enabled: true
            }
        });
    }
    
    // Function to check if element is in viewport
    function isInViewport(element) {
        var elementTop = $(element).offset().top;
        var elementBottom = elementTop + $(element).outerHeight();
        var viewportTop = $(window).scrollTop();
        var viewportBottom = viewportTop + $(window).height();
        return elementBottom > viewportTop && elementTop < viewportBottom;
    }
    
    // Animated number counting for stats
    var statsAnimated = false;
    
    function animateStats() {
        if (!statsAnimated && isInViewport('.stats-container')) {
            statsAnimated = true;
            $('.stat-value, .result-value').each(function () {
                var $this = $(this);
                var text = $this.text();
                var countTo = parseInt(text.replace(/\D/g, ''), 10);
                
                if (isNaN(countTo)) return;
                
                $({ countNum: 0 }).animate({
                    countNum: countTo
                },
                {
                    duration: 2000,
                    easing: 'swing',
                    step: function() {
                        var formattedValue = Math.floor(this.countNum);
                        if (text.indexOf('%') !== -1) {
                            formattedValue = formattedValue + '%';
                        } else if (text.match(/[^\d]/)) {
                            // If original text contains non-digit characters (like units)
                            formattedValue = formattedValue + text.replace(/\d+/g, '');
                        }
                        $this.text(formattedValue);
                    },
                    complete: function() {
                        $this.text(text);
                    }
                });
            });
        }
    }
    
    // Check on scroll and on page load
    $(window).on('scroll load', animateStats);
});
</script>

<?php get_footer(); ?>
